from desafio_aves_herencia import pepita, chimuelo, caro, maria

# print(pepita)
# print("Energia al principio:", pepita.energia)
# print("Entrena", pepita.entrenamiento())
# print("Energia post-entrenar:", pepita.energia)
# print("Entrena fuerte", pepita.entrenamiento_intensivo())
# print("Energia post-entrenamientos:", pepita.energia)
# print(pepita.esta_debil())

# print(maria)
# print("Energia al principio:", maria.energia)
# print("Entrena", maria.entrenamiento())
# print("Energia post-entrenar:", maria.energia)
# print("Entrena fuerte", maria.entrenamiento_intensivo())
# print("Energia post-entrenamientos:", maria.energia)
# print(maria.esta_debil())

# print(chimuelo)
# print("Energia al principio:", chimuelo.energia)
# print("Entrena", chimuelo.entrenamiento())
# print("Energia post-entrenar:", chimuelo.energia)
# print("Entrena fuerte", chimuelo.entrenamiento_intensivo())
# print("Energia post-entrenamientos:", chimuelo.energia)
# print(chimuelo.esta_debil())

# print(caro)
# print(caro.energia)
# print(caro.corre_en_circulos())
# print(caro.energia)
